  ARCHER:
    name: "Archer"
    type: "normal"
    shop_material: "BOW"
    levels:
      1:
        cost: 10
        damage: 15
        reload: 1.5
        range: 10
        splash: 0
      2:
        cost: 90
        damage: 50
        reload: 1.25
        range: 11
        splash: 0
      3:
        cost: 1340
        damage: 250
        reload: 1.0
        range: 12
        splash: 0
    prestiges:
      1:
        name: "Archer IV - Sniper"
        shop_material: "BOW"
        cost: 21340
        damage: 5000
        reload: 2.0
        range: 30
        splash: 0
        special: "Long Range//Focus monsters with 50% more HP in priority//and inflict them twice the damage "
      2:
        name: "Archer IV - Machine Gun"
        shop_material: "WHEAT_SEEDS"
        cost: 21340
        damage: 2400
        reload: 0.75
        range: 10
        splash: 0
        special: "Very fast firing rate"

  SLIME:
    name: "Slime"
    type: "normal"
    shop_material: "SLIME_BLOCK"
    levels:
      1:
        cost: 50
        damage: 6
        reload: 1.5
        range: 8
        splash: 4
        special: "Splash damage//Slow down monsters for 4 seconds"
      2:
        cost: 650
        damage: 25
        reload: 1.25
        range: 9
        splash: 5
        special: "Splash damage//Slow down monsters for 4 seconds"
      3:
        cost: 8650
        damage: 150
        reload: 1.0
        range: 10
        splash: 6
        special: "Splash damage//Slow down monsters for 4 seconds"
    prestiges:
      1:
        name: "Slime IV - Sticky Tower"
        shop_material: "STICKY_PISTON"
        cost: 38650
        damage: 500
        reload: 1.0
        range: 10
        splash: 1
        special: "Very low splash radius//Slow down monsters for 4 seconds//Very powerful slow"
      2:
        name: "Slime IV - Big Slime"
        shop_material: "SLIME_BLOCK"
        cost: 38650
        damage: 250
        reload: 1.0
        range: 12
        splash: 8
        special: "Slow down monsters for 4 seconds//Increased splash and slow effect"

  MAGMA:
    name: "Magma"
    type: "normal"
    shop_material: "MAGMA_CREAM"
    levels:
      1:
        cost: 125
        damage: 75
        reload: 1.5
        range: 7
        splash: 2
        special: "Splash damage"
      2:
        cost: 1625
        damage: 200
        reload: 1.25
        range: 8
        splash: 4
        special: "Splash damage"
      3:
        cost: 13625
        damage: 450
        reload: 1.0
        range: 9
        splash: 6
        special: "Splash damage"
    prestiges:
      1:
        name: "Magma IV - Infernal Tower"
        shop_material: "FLINT_AND_STEEL"
        cost: 63625
        damage: 1000
        reload: 1.0
        range: 9
        splash: 6
        special: "Burn monsters for 5 seconds//Burning monsters lose 0.5% HP per second"
      2:
        name: "Magma IV - Volcano"
        shop_material: "LAVA_BUCKET"
        cost: 63625
        damage: 1000
        reload: 1.0
        range: 9
        splash: 6
        stun: 0.05
        special: "Low chance to stun monsters//Stunned monsters can't move or act"

  WITCH:
    name: "Witch"
    type: "support"
    shop_material: "CARVED_PUMPKIN"
    levels:
      1:
        cost: 250
        damage: 25
        reload: 1.25
        range: 10
        splash: 0
        weakness: 0.40
        special: "Apply weakness to monsters for 10 seconds//Weakness lower monsters defence by 40%"
      2:
        cost: 5250
        damage: 100
        reload: 0.75
        range: 10
        splash: 0
        weakness: 0.80
        special: "Apply weakness to monsters for 10 seconds//Weakness lower monsters defence by 80%//Hit unaffected monsters in priority"

  ENDERMAN:
    name: "Enderman"
    type: "support"
    shop_material: "ENDER_EYE"
    levels:
      1:
        cost: 2500
        damage: 0
        reload: 60.0
        range: 8
        splash: 0
        special: "Teleport 1 monster back//Long reload time"
      2:
        cost: 27500
        damage: 0
        reload: 45.0
        range: 8
        splash: 0
        special: "Teleport 1 monster back//Damage 10% of monster's current health//Long reload time"

  VILLAGER:
    name: "Villager"
    type: "support"
    shop_material: "HOPPER"
    levels:
      1:
        cost: 1000
        damage: 0
        reload: 0
        range: 5
        splash: 0
        special: "Prevent nearby towers to//be affected by bad effects"
      2:
        cost: 26000
        damage: 0
        reload: 0
        range: 10
        splash: 0
        special: "Prevent nearby towers to//be affected by bad effects//+10% speed for nearby towers"

  GUARDIAN:
    name: "Guardian"
    type: "normal"
    shop_material: "PRISMARINE_SHARD"
    levels:
      1:
        cost: 200
        damage: 140
        reload: 2.0
        range: 6
        splash: 0
        special: "Pierces through multiple monsters//in line with a deadly laser"
      2:
        cost: 1500
        damage: 500
        reload: 2.0
        range: 6
        splash: 0
        special: "Pierces through multiple monsters//in line with a deadly laser"
      3:
        cost: 11500
        damage: 1500
        reload: 2.0
        range: 6
        splash: 0
        special: "Pierces through multiple monsters//in line with a deadly laser"
    prestiges:
      1:
        name: "Guardian IV - Mind Control"
        shop_material: "GOLD_BLOCK"
        cost: 51500
        damage: 2000
        reload: 2.0
        range: 8
        splash: 0
        special: "30% chance of causing a nearby//monster to walk backwards for 3 seconds"
      2:
        name: "Guardian IV - Fatigue"
        shop_material: "DIAMOND_BLOCK"
        cost: 51500
        damage: 2000
        reload: 2.0
        range: 8
        splash: 0
        special: "Disables the special ability//of a nearby monster for 5 seconds"

  TESLA:
    name: "Tesla"
    type: "normal"
    shop_material: "BEACON"
    levels:
      1:
        cost: 200
        damage: 75
        reload: 1.0
        range: 8
        splash: 0
        special: "Targets the monster which is//farthest from exit until it leaves its range//Damage increases with each attack on//the same target up to a maximum of 200%."
      2:
        cost: 2000
        damage: 500
        reload: 1.0
        range: 10
        splash: 0
        special: "Targets the monster which is//farthest from exit until it leaves its range//Damage increases with each attack on//the same target up to a maximum of 200%."
      3:
        cost: 12000
        damage: 2000
        reload: 1.0
        range: 12
        splash: 0
        special: "Targets the monster which is//farthest from exit until it leaves its range//Damage increases with each attack on//the same target up to a maximum of 200%."
    prestiges:
      1:
        name: "Tesla IV - Beam"
        shop_material: "GOLD_BLOCK"
        cost: 37000
        damage: 2000
        reload: 1.0
        range: 12
        splash: 0
        special: "Targets the monster which is//farthest from exit until it leaves its range//Damage increases with each attack//on the same target without limit.//Applies slowness."
      2:
        name: "Tesla IV - Lightning"
        shop_material: "DIAMOND_BLOCK"
        cost: 37000
        damage: 3000
        reload: 1.0
        range: 16
        splash: 0
        special: "Targets the monster which is//farthest from exit until it leaves its range//Damage increases with each attack get//saved between targets and can go as high as 300%."